name: CI

on: [pull_request]

jobs:
  Build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
      - name: Build project
        run: ./gradlew assembleDebug
      - name: Run tests
        run: ./gradlew test

